# Artificial Neural Network

### Importing the libraries

In [4]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [5]:
tf.__version__

'2.2.0'

### Importing the dataset

In [6]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [7]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [8]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data

Label Encoding the "Gender" column

In [9]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [10]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [11]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [12]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the dataset into the Training set and Test set

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Feature Scaling

In [14]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

### Initializing the ANN

In [15]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [16]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [17]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [18]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Training the ANN

### Compiling the ANN

In [19]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set

In [20]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 0s 864us/step - loss: 0.5284 - accuracy: 0.7936
Epoch 2/100
250/250 [==============================] - 0s 789us/step - loss: 0.4615 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 0s 809us/step - loss: 0.4429 - accuracy: 0.7966
Epoch 4/100
250/250 [==============================] - 0s 832us/step - loss: 0.4333 - accuracy: 0.8048
Epoch 5/100
250/250 [==============================] - 0s 795us/step - loss: 0.4276 - accuracy: 0.8105
Epoch 6/100
250/250 [==============================] - 0s 817us/step - loss: 0.4237 - accuracy: 0.8154
Epoch 7/100
250/250 [==============================] - 0s 807us/step - loss: 0.4205 - accuracy: 0.8173
Epoch 8/100
250/250 [==============================] - 0s 883us/step - loss: 0.4175 - accuracy: 0.8189
Epoch 9/100
250/250 [==============================] - 0s 801us/step - loss: 0.4150 - accuracy: 0.8216
Epoch 10/100
250/250 [==============================] - 0s 900us/step - l

250/250 [==============================] - 0s 822us/step - loss: 0.3377 - accuracy: 0.8611
Epoch 80/100
250/250 [==============================] - 0s 808us/step - loss: 0.3373 - accuracy: 0.8606
Epoch 81/100
250/250 [==============================] - 0s 833us/step - loss: 0.3373 - accuracy: 0.8615
Epoch 82/100
250/250 [==============================] - 0s 820us/step - loss: 0.3372 - accuracy: 0.8616
Epoch 83/100
250/250 [==============================] - 0s 800us/step - loss: 0.3373 - accuracy: 0.8619
Epoch 84/100
250/250 [==============================] - 0s 842us/step - loss: 0.3373 - accuracy: 0.8606
Epoch 85/100
250/250 [==============================] - 0s 829us/step - loss: 0.3372 - accuracy: 0.8611
Epoch 86/100
250/250 [==============================] - 0s 815us/step - loss: 0.3372 - accuracy: 0.8615
Epoch 87/100
250/250 [==============================] - 0s 803us/step - loss: 0.3374 - accuracy: 0.8618
Epoch 88/100
250/250 [==============================] - 0s 792us/step - loss:

### Predicting the result of a single observation



Predit whether the following customer will leave the bank

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card ? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer ?

**Result**

In [21]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

[[False]]


The ANN model predicts that this customer stays in the bank!


### Predicting the Test set results

In [22]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [23]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1514   81]
 [ 197  208]]


0.861