# Artificial Neural Network
Predit whether a customer leave a bank or not

In [17]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential

In [18]:
tf.__version__

'2.4.1'

### Import dataset

In [19]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [20]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [21]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data

Label Encoding the "Gender" column

In [22]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [23]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [24]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [25]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the dataset into the Training set and Test set

In [26]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Feature Scaling

In [27]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

### Create ANN Model

In [34]:
ann_model = Sequential()
ann_model.add(tf.keras.layers.Dense(units=6, activation='relu'))
ann_model.add(tf.keras.layers.Dense(units=6, activation='relu'))
ann_model.add(tf.keras.layers.Dense(units=6, activation='relu'))
ann_model.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

### Compile ANN Model

In [35]:
ann_model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training ANN Model

In [43]:
history = ann_model.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 0s 893us/step - loss: 0.3283 - accuracy: 0.8649
Epoch 2/100
250/250 [==============================] - 0s 837us/step - loss: 0.3284 - accuracy: 0.8641
Epoch 3/100
250/250 [==============================] - 0s 823us/step - loss: 0.3284 - accuracy: 0.8650
Epoch 4/100
250/250 [==============================] - 0s 810us/step - loss: 0.3277 - accuracy: 0.8658
Epoch 5/100
250/250 [==============================] - 0s 812us/step - loss: 0.3285 - accuracy: 0.8633
Epoch 6/100
250/250 [==============================] - 0s 814us/step - loss: 0.3281 - accuracy: 0.8655
Epoch 7/100
250/250 [==============================] - 0s 821us/step - loss: 0.3286 - accuracy: 0.8660
Epoch 8/100
250/250 [==============================] - 0s 842us/step - loss: 0.3285 - accuracy: 0.8654
Epoch 9/100
250/250 [==============================] - 0s 817us/step - loss: 0.3281 - accuracy: 0.8656
Epoch 10/100
250/250 [==============================] - 0s 827us/step - l

250/250 [==============================] - 0s 825us/step - loss: 0.3277 - accuracy: 0.8641
Epoch 80/100
250/250 [==============================] - 0s 827us/step - loss: 0.3256 - accuracy: 0.8659
Epoch 81/100
250/250 [==============================] - 0s 790us/step - loss: 0.3259 - accuracy: 0.8673
Epoch 82/100
250/250 [==============================] - 0s 806us/step - loss: 0.3273 - accuracy: 0.8673
Epoch 83/100
250/250 [==============================] - 0s 846us/step - loss: 0.3253 - accuracy: 0.8670
Epoch 84/100
250/250 [==============================] - 0s 803us/step - loss: 0.3267 - accuracy: 0.8658
Epoch 85/100
250/250 [==============================] - 0s 795us/step - loss: 0.3259 - accuracy: 0.8660
Epoch 86/100
250/250 [==============================] - 0s 816us/step - loss: 0.3270 - accuracy: 0.8658
Epoch 87/100
250/250 [==============================] - 0s 808us/step - loss: 0.3264 - accuracy: 0.8655
Epoch 88/100
250/250 [==============================] - 0s 824us/step - loss:

### Predicting the result of a single observation



Predit whether the following customer will leave the bank

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card ? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer ?

**Result**

In [44]:
print(ann_model.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

[[False]]


The ANN model predicts that this customer stays in the bank!


### Predicting the Test set results

In [45]:
y_pred = ann_model.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [55]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1496   99]
 [ 177  228]]


0.862

In [56]:
ann_model.save('customer_management.h5', overwrite=True)